export type QuoteCategory = "risk" | "mindset" | "patience" | "life";

export interface Quote {
  category: QuoteCategory;
  text: string;
}

export const QUOTE_CATEGORY_LABEL: Record<QuoteCategory, string> = {
  risk: "Risk & losses",
  mindset: "Mindset & execution",
  patience: "Patience & waiting",
  life: "Life",
};

const RISK_QUOTES: Quote[] = [
  { category: "risk", text: "Protect capital first, profits second." },
  {
    category: "risk",
    text: "If you can't take small losses, sooner or later you will take the mother of all losses.",
  },
  { category: "risk", text: "Cut losses quickly, let winners run." },
  { category: "risk", text: "The market can stay irrational longer than you can stay solvent." },
  { category: "risk", text: "Risk management is the only edge that never stops working." },
  { category: "risk", text: "A loss is just the cost of doing business." },
  { category: "risk", text: "Never risk more than you can afford to lose on a single trade." },
  { category: "risk", text: "The first loss is the best loss." },
  { category: "risk", text: "Size your position for the worst case, not the best." },
  { category: "risk", text: "Capital preservation is a full-time job." },
  { category: "risk", text: "Every trade should have a predefined exit before it has an entry." },
  { category: "risk", text: "Position sizing decides who survives the drawdown." },
  { category: "risk", text: "A stop loss is not a suggestion." },
  { category: "risk", text: "The market doesn't know how much you need to make back." },
  { category: "risk", text: "Risk of ruin is the only risk that matters." },
  { category: "risk", text: "One oversized trade can erase a year of discipline." },
  { category: "risk", text: "Leverage magnifies both skill and stupidity." },
  { category: "risk", text: "Don't average down into a losing thesis." },
  { category: "risk", text: "A small loss taken today is cheaper than a big loss taken tomorrow." },
  { category: "risk", text: "Survival is the first strategy, everything else is second." },
  { category: "risk", text: "The account that survives the drawdown gets to see the recovery." },
  { category: "risk", text: "Revenge trading turns one loss into three." },
  { category: "risk", text: "Correlation risk hides until everything moves together." },
  { category: "risk", text: "Hope is not a risk management strategy." },
  { category: "risk", text: "Know your max loss before you know your max gain." },
  { category: "risk", text: "The market doesn't punish risk, it punishes unmanaged risk." },
  { category: "risk", text: "A trade without a stop is a trade without a plan." },
  { category: "risk", text: "Every position is a bet against your own certainty." },
  { category: "risk", text: "Overleveraging turns a good idea into a bad outcome." },
  { category: "risk", text: "Small losses keep you in the game long enough to win." },
  { category: "risk", text: "The size of the loss matters more than the fact of the loss." },
  { category: "risk", text: "Risk what you can lose, not what you need." },
  { category: "risk", text: "A drawdown is a math problem before it's an emotional one." },
  { category: "risk", text: "Cutting a loss early is not weakness, it's strategy." },
  { category: "risk", text: "Never let a winning trade turn into a loss out of greed." },
  { category: "risk", text: "The market will find the one position you didn't hedge." },
  { category: "risk", text: "Concentration risk is invisible until it isn't." },
  { category: "risk", text: "A stop loss protects your capital and your clarity." },
  { category: "risk", text: "The goal isn't to be right, it's to lose small when you're wrong." },
  { category: "risk", text: "Black swans don't ask for permission." },
  { category: "risk", text: "Your risk limit should be set before the trade excites you." },
  { category: "risk", text: "A losing streak reveals your risk management, not your luck." },
  { category: "risk", text: "The market has no memory of how much you've already lost." },
  { category: "risk", text: "Don't let one trade decide your month." },
  { category: "risk", text: "Insurance costs money; ruin costs everything." },
  { category: "risk", text: "The best traders lose often and lose small." },
  { category: "risk", text: "Position size is the only variable you fully control." },
  { category: "risk", text: "A blown account teaches the lesson risk management was trying to prevent." },
  { category: "risk", text: "Every edge disappears without risk control behind it." },
  { category: "risk", text: "The market doesn't care about your average entry price." },
  { category: "risk", text: "Doubling down on a loser is doubling your risk of ruin." },
  { category: "risk", text: "Protecting downside protects your ability to capture upside." },
  { category: "risk", text: "Risk first, reward second, ego never." },
  { category: "risk", text: "A trade plan without a max loss isn't a plan." },
  { category: "risk", text: "The fastest way to blow up is to trade like you can't lose." },
  { category: "risk", text: "Drawdowns are the tuition of this business." },
  { category: "risk", text: "Never risk your peace of mind for a trade that isn't there yet." },
  { category: "risk", text: "The market takes the most from those who respect it the least." },
  { category: "risk", text: "One unhedged black swan can undo a decade of gains." },
  { category: "risk", text: "Smaller size buys you more time to be wrong." },
  { category: "risk", text: "Capital is the only tool you can't trade without." },
  { category: "risk", text: "The trade you didn't take can't hurt you." },
  { category: "risk", text: "Risk management is invisible until the day it saves you." },
  { category: "risk", text: "Losing is part of the process; losing big is a failure of process." },
  { category: "risk", text: "Don't let a winning streak convince you risk doesn't apply to you." },
  { category: "risk", text: "A stop loss hit is a plan working, not a plan failing." },
  { category: "risk", text: "The market has no obligation to prove you right." },
  { category: "risk", text: "Every dollar of risk should have a reason attached to it." },
  { category: "risk", text: "Trading without a max loss is gambling with extra steps." },
  {
    category: "risk",
    text: "The size of your position should match the size of your conviction, not your fear of missing out.",
  },
  { category: "risk", text: "A good trader is a risk manager who occasionally trades." },
  { category: "risk", text: "The market rewards those who respect the downside." },
  { category: "risk", text: "Protect the account so the account can protect you." },
  { category: "risk", text: "Overconfidence writes checks your risk management can't cash." },
  { category: "risk", text: "The only guaranteed loss is the one you didn't plan for." },
  { category: "risk", text: "Every position carries a hidden cost: the risk of being wrong." },
  { category: "risk", text: "Risk control is the difference between a bad month and a blown account." },
  { category: "risk", text: "Don't confuse a lucky trade with a good risk decision." },
  { category: "risk", text: "The market can turn a small mistake into a permanent one if you let it." },
  { category: "risk", text: "A trade that risks too much to be right is already a mistake." },
  { category: "risk", text: "Manage risk like your career depends on it, because it does." },
  { category: "risk", text: "A single unmanaged loss can undo a hundred managed wins." },
  { category: "risk", text: "The exit plan matters more than the entry signal." },
  { category: "risk", text: "Never trade size you can't sleep with." },
  { category: "risk", text: "The market doesn't care about your break-even price." },
  { category: "risk", text: "A good risk manager survives to trade another cycle." },
  { category: "risk", text: "Losses are tuition; unmanaged losses are debt." },
  { category: "risk", text: "Respect the downside and the upside takes care of itself." },
  { category: "risk", text: "A trader who never loses small eventually loses everything." },
  { category: "risk", text: "Risk is the price of admission; ruin is the price of carelessness." },
];

const MINDSET_QUOTES: Quote[] = [
  { category: "mindset", text: "Markets don't care about your opinion—only your execution matters." },
  { category: "mindset", text: "Plan the trade, trade the plan." },
  { category: "mindset", text: "Discipline beats intelligence in the long run." },
  { category: "mindset", text: "Your worst enemy in trading is the one in the mirror." },
  { category: "mindset", text: "Emotion is the tax you pay for not having a plan." },
  { category: "mindset", text: "Consistency comes from process, not prediction." },
  { category: "mindset", text: "Trade what you see, not what you think." },
  { category: "mindset", text: "The market rewards discipline, not conviction." },
  { category: "mindset", text: "Execution without hesitation is the edge." },
  { category: "mindset", text: "Being right and making money are two different skills." },
  { category: "mindset", text: "Confidence without discipline is just a louder way to lose." },
  { category: "mindset", text: "The best traders are boring on purpose." },
  { category: "mindset", text: "Your P&L is a mirror of your discipline, not your intelligence." },
  { category: "mindset", text: "Hesitation costs more than being wrong." },
  { category: "mindset", text: "A good process will lose sometimes and still be right." },
  { category: "mindset", text: "Chasing the market is how the market catches you." },
  { category: "mindset", text: "FOMO is not a strategy." },
  { category: "mindset", text: "The trade you didn't take is not a mistake if it wasn't your setup." },
  { category: "mindset", text: "Journaling turns mistakes into data instead of drama." },
  { category: "mindset", text: "Your edge lives in your rules, not your feelings." },
  { category: "mindset", text: "Overtrading is boredom dressed up as opportunity." },
  { category: "mindset", text: "The market punishes impulsive execution more than bad analysis." },
  { category: "mindset", text: "Discipline is choosing the plan over the impulse, every single time." },
  { category: "mindset", text: "A trader without rules is a gambler with better vocabulary." },
  { category: "mindset", text: "Conviction should come from the setup, not from the need to be right." },
  { category: "mindset", text: "The goal is not to predict the market, it's to react to it well." },
  { category: "mindset", text: "Your process is the only thing you fully control." },
  { category: "mindset", text: "Confidence is earned in the replay, not in the moment." },
  { category: "mindset", text: "Execution is where good analysis goes to die or thrive." },
  { category: "mindset", text: "Every rule you break becomes a rule you'll break again." },
  { category: "mindset", text: "The market doesn't reward hope, it rewards preparation." },
  { category: "mindset", text: "Trading well is mostly about not trading badly." },
  { category: "mindset", text: "Emotional trades are retroactively justified, rarely planned." },
  { category: "mindset", text: "The best trade is sometimes the one you don't take." },
  { category: "mindset", text: "Discipline is remembering the plan when the moment forgets it." },
  { category: "mindset", text: "A trader's biggest leak is usually behavioral, not technical." },
  { category: "mindset", text: "React to the market, don't argue with it." },
  { category: "mindset", text: "Your rules exist for the moments you don't want to follow them." },
  { category: "mindset", text: "The market will test your discipline before it rewards your analysis." },
  { category: "mindset", text: "Consistency is a decision made before the trade, not during it." },
  { category: "mindset", text: "Every deviation from the plan is a new, unbacktested strategy." },
  { category: "mindset", text: "Trading is a game of self-management disguised as a game of markets." },
  { category: "mindset", text: "The market doesn't know your account balance, only your behavior does." },
  { category: "mindset", text: "Good execution feels boring; bad execution feels exciting." },
  { category: "mindset", text: "A trader's ego is the most expensive position in the account." },
  { category: "mindset", text: "The plan is only as good as your willingness to follow it." },
  { category: "mindset", text: "Discipline is a muscle that atrophies the moment you stop training it." },
  { category: "mindset", text: "Reacting fast is not the same as reacting well." },
  { category: "mindset", text: "The market is neutral; your interpretation is where the risk begins." },
  { category: "mindset", text: "Trade your plan, not your last trade." },
  { category: "mindset", text: "Confidence built on a losing streak is the most dangerous kind." },
  { category: "mindset", text: "Every trader has a plan until the market tests their patience." },
  { category: "mindset", text: "Execution is the bridge between a good idea and a good outcome." },
  { category: "mindset", text: "The market doesn't care how hard you worked on the analysis." },
  { category: "mindset", text: "Process over outcome, every single time." },
  { category: "mindset", text: "A disciplined loss is more valuable than a lucky win." },
  { category: "mindset", text: "Your worst trades usually start with \"just this once.\"" },
  { category: "mindset", text: "The mind that panics first usually pays the most." },
  { category: "mindset", text: "Trading well means being comfortable being uncomfortable." },
  { category: "mindset", text: "Rules are cheaper than the lessons that create them." },
  { category: "mindset", text: "A trader who chases the last trade loses the next one too." },
  { category: "mindset", text: "Execution reveals what preparation only promised." },
  { category: "mindset", text: "The market has no opinion of you; stop trading like it does." },
  { category: "mindset", text: "Discipline is doing the boring thing at the exciting moment." },
  { category: "mindset", text: "Your edge is only as strong as your worst emotional day." },
  { category: "mindset", text: "Good habits compound the same way good trades do." },
  { category: "mindset", text: "React to price, not to the noise around it." },
  { category: "mindset", text: "The best traders make peace with being wrong quickly." },
  { category: "mindset", text: "A trading plan is a promise to your future, calmer self." },
  { category: "mindset", text: "Impulse is expensive; patience is free." },
  { category: "mindset", text: "The market is a mirror—it reflects your discipline back at you." },
  { category: "mindset", text: "Every great trader was once a disciplined beginner." },
  { category: "mindset", text: "Trading badly with good analysis is still trading badly." },
  { category: "mindset", text: "The setup doesn't care about your mood." },
  { category: "mindset", text: "Consistency is built one boring, correct decision at a time." },
  { category: "mindset", text: "A trader's job is to execute, not to predict." },
  { category: "mindset", text: "The market forgives good process even when it doesn't forgive the outcome." },
  { category: "mindset", text: "Emotional discipline is the real technical indicator." },
  { category: "mindset", text: "Trade small when your mind is loud." },
  { category: "mindset", text: "The best entries feel calm, not urgent." },
  { category: "mindset", text: "A rule followed under pressure is worth more than a rule written on paper." },
  { category: "mindset", text: "Reacting emotionally to a loss guarantees a second one." },
  { category: "mindset", text: "Your process should survive contact with a bad day." },
  { category: "mindset", text: "The market doesn't owe you a trade just because you're watching it." },
  { category: "mindset", text: "Discipline in small decisions builds discipline in big ones." },
  { category: "mindset", text: "A trader who can't sit still can't wait for the good trades." },
  { category: "mindset", text: "Execution is a skill, not a personality trait—it can be trained." },
  { category: "mindset", text: "The market rewards those who show up the same way every day." },
  { category: "mindset", text: "Your plan is only tested on the days you don't want to follow it." },
  {
    category: "mindset",
    text: "Mastery in trading looks like doing the same right thing, calmly, again and again.",
  },
];

const PATIENCE_QUOTES: Quote[] = [
  { category: "patience", text: "The big money is made by sitting, not trading." },
  { category: "patience", text: "Wait for the setup; don't force the trade." },
  { category: "patience", text: "Boredom is the price of good discipline." },
  { category: "patience", text: "Patience is a position too." },
  { category: "patience", text: "The market will still be there tomorrow—your capital might not be." },
  { category: "patience", text: "Not trading is a trade too." },
  { category: "patience", text: "Good trades come to those who wait for them." },
  { category: "patience", text: "Impatience is the most expensive habit in trading." },
  { category: "patience", text: "Let the trade come to you." },
  { category: "patience", text: "Do nothing until there is something to do." },
  { category: "patience", text: "The best opportunities rarely arrive on your schedule." },
  { category: "patience", text: "Sitting on your hands is sometimes the hardest trade of all." },
  { category: "patience", text: "A missed trade costs nothing; a forced one can cost everything." },
  { category: "patience", text: "Waiting for confirmation is cheaper than chasing a hope." },
  { category: "patience", text: "The market rewards those who can do nothing gracefully." },
  { category: "patience", text: "Patience turns a good setup into a great trade." },
  { category: "patience", text: "There is no penalty for waiting for the right price." },
  { category: "patience", text: "A watched setup that never triggers is still a win if you didn't force it." },
  { category: "patience", text: "The hardest skill in trading is waiting without anxiety." },
  { category: "patience", text: "Cash is a position, and sometimes the best one." },
  { category: "patience", text: "The market doesn't reward urgency, it rewards timing." },
  { category: "patience", text: "Every great trade started with someone willing to wait for it." },
  { category: "patience", text: "Patience is the discount you pay for a better entry." },
  { category: "patience", text: "Chasing price is the opposite of waiting for it." },
  { category: "patience", text: "A trader in a hurry is a trader about to overpay." },
  { category: "patience", text: "The setup you wait for is worth more than the one you settle for." },
  { category: "patience", text: "Sometimes the best action is inaction, held with conviction." },
  { category: "patience", text: "Time in the market matters less than timing your entries with patience." },
  { category: "patience", text: "The market punishes those who can't sit still." },
  { category: "patience", text: "Waiting is not losing; it's preserving optionality." },
  { category: "patience", text: "A trade delayed by discipline beats a trade rushed by impulse." },
  { category: "patience", text: "Let the setup fully form before you act on it." },
  { category: "patience", text: "Patience compounds just like capital does." },
  { category: "patience", text: "The market gives its best trades to those who aren't desperate for one." },
  { category: "patience", text: "Nothing is often the correct, if uncomfortable, answer." },
  { category: "patience", text: "A trader's patience is tested most right before the good setup arrives." },
  { category: "patience", text: "Waiting for the \"A+\" setup is cheaper than trading the \"C\" one." },
  { category: "patience", text: "The urge to trade is not the same as an actual opportunity." },
  { category: "patience", text: "Good things come to those who don't force bad trades while waiting." },
  { category: "patience", text: "Patience is the quiet skill behind every loud winning trade." },
  { category: "patience", text: "The market has no deadline for you to make money." },
  { category: "patience", text: "Sitting in cash is not the same as sitting on the sidelines of opportunity." },
  { category: "patience", text: "Every setup has a season; don't trade it out of season." },
  { category: "patience", text: "The best trades often feel like they took forever to arrive." },
  { category: "patience", text: "Waiting for the trend to confirm beats guessing at the reversal." },
  { category: "patience", text: "Boredom before the trade is better than regret after it." },
  { category: "patience", text: "A trader who can wait a week can wait for the right trade." },
  { category: "patience", text: "The market's patience with your capital is not infinite; match it with your own." },
  { category: "patience", text: "Discipline is most visible in the trades you didn't take." },
  { category: "patience", text: "Let conviction build before commitment does." },
  { category: "patience", text: "A rushed entry is a discount you pay yourself for impatience." },
  { category: "patience", text: "Waiting costs nothing; forcing costs everything." },
  { category: "patience", text: "The best traders treat \"no trade\" as a valid outcome." },
  { category: "patience", text: "Give the setup time to prove itself before you commit capital." },
  { category: "patience", text: "The market moves in its own time, not yours." },
  { category: "patience", text: "Patience protects you from the trade that looked good but wasn't ready." },
  { category: "patience", text: "Sometimes the trade you don't take is the best trade of the week." },
  { category: "patience", text: "A calm wait beats an anxious entry every time." },
  { category: "patience", text: "The setup that makes you wait is often the one worth waiting for." },
  { category: "patience", text: "Trading less can mean earning more." },
  { category: "patience", text: "The market has no urgency; borrowing its patience is free." },
  { category: "patience", text: "Impulse says now; patience says when it's ready." },
  { category: "patience", text: "A trader's edge grows every time they choose to wait instead of force." },
  { category: "patience", text: "The best entries are boring right up until they aren't." },
  { category: "patience", text: "Waiting is a skill you can practice on every trade you skip." },
  { category: "patience", text: "The setup will tell you when it's ready—listen for it." },
  { category: "patience", text: "Every good trade has a version of you that almost didn't wait for it." },
  { category: "patience", text: "Patience is invisible until you look at the account that had it." },
  { category: "patience", text: "The urge to act is strongest right before the wrong time to act." },
  { category: "patience", text: "A trader who waits well trades less and keeps more." },
  { category: "patience", text: "Let the market prove itself before you prove yourself right." },
  { category: "patience", text: "The best setups reward those who saw them coming and still waited." },
  { category: "patience", text: "Do less, wait more, and let the good trades find you." },
  { category: "patience", text: "Patience is the only indicator that never lags." },
  { category: "patience", text: "A trade rushed is a trade half-planned." },
  { category: "patience", text: "The market's silence is not an invitation to force noise into it." },
  { category: "patience", text: "Waiting for the close is cheaper than guessing the open." },
  { category: "patience", text: "Good things come slowly, and disappear quickly if rushed." },
  { category: "patience", text: "A trader in no hurry rarely overpays." },
  { category: "patience", text: "The setup owes you nothing until it's actually there." },
  { category: "patience", text: "Patience is the discipline that makes all the other discipline possible." },
  { category: "patience", text: "Every setup you wait for correctly builds trust in your own process." },
  { category: "patience", text: "The trade will still be there after you've confirmed it." },
  { category: "patience", text: "Sitting still is a position, and often the right one." },
  {
    category: "patience",
    text: "The best traders are patient with the market and impatient with their own excuses.",
  },
  { category: "patience", text: "A good wait is never wasted, even if the trade never comes." },
  { category: "patience", text: "The market has cycles; patience is how you trade with them, not against them." },
  { category: "patience", text: "Waiting for proof beats trading on hope." },
  { category: "patience", text: "A trader who can wait out of boredom has already mastered half the game." },
  { category: "patience", text: "The reward for patience is a trade that didn't need forcing." },
];

const LIFE_QUOTES: Quote[] = [
  { category: "life", text: "Life is awesome when you build something with consistency." },
  { category: "life", text: "Small daily actions compound into a life you're proud of." },
  { category: "life", text: "Discipline in the little things builds freedom in the big things." },
  { category: "life", text: "The days you don't feel like showing up are the ones that matter most." },
  { category: "life", text: "Consistency is the quiet secret behind every \"overnight\" success." },
  { category: "life", text: "You don't need motivation if you have a system." },
  { category: "life", text: "What you repeat, you become." },
  { category: "life", text: "Progress hides in the boring, repeated days." },
  { category: "life", text: "Showing up daily beats showing up perfectly." },
  { category: "life", text: "A life built brick by brick outlasts one built overnight." },
  { category: "life", text: "The compound interest of good habits is the most underrated force in life." },
  { category: "life", text: "Consistency turns ordinary effort into extraordinary results." },
  { category: "life", text: "You are the average of what you do every single day." },
  { category: "life", text: "Small wins repeated become a life transformed." },
  { category: "life", text: "Discipline today is freedom tomorrow." },
  { category: "life", text: "The days that feel unremarkable are often the ones building the most." },
  { category: "life", text: "Consistency doesn't ask for talent, just for showing up." },
  { category: "life", text: "Build your life the same way you'd build good trades: with patience and a plan." },
  { category: "life", text: "Every streak starts with a day you almost skipped." },
  { category: "life", text: "The best version of you is built one repeated day at a time." },
  { category: "life", text: "Habits are votes for the person you're becoming." },
  { category: "life", text: "A consistent life is a quiet rebellion against a distracted world." },
  { category: "life", text: "You don't rise to your goals, you fall to your habits." },
  {
    category: "life",
    text: "The reward for consistency always arrives later than you'd like, and bigger than you'd expect.",
  },
  {
    category: "life",
    text: "Life rewards the same discipline the market does: patience, process, and repetition.",
  },
  { category: "life", text: "Small, boring, repeated actions are how big, exciting lives get built." },
  { category: "life", text: "The version of you a year from now is being built today." },
  { category: "life", text: "Consistency is the bridge between who you are and who you want to be." },
  { category: "life", text: "Every good habit is a small trade with a very long time horizon." },
  { category: "life", text: "Show up today, and let the compounding take care of the rest." },
];

// Life is a deliberately rare 1-in-10 - the cycle repeats every 10 days
// with three risk/mindset/patience days apiece and a single life day, so
// the ratio holds exactly regardless of how long the app has been used.
const CATEGORY_CYCLE: QuoteCategory[] = [
  "risk",
  "mindset",
  "patience",
  "risk",
  "mindset",
  "patience",
  "risk",
  "mindset",
  "patience",
  "life",
];

const QUOTES_BY_CATEGORY: Record<QuoteCategory, Quote[]> = {
  risk: RISK_QUOTES,
  mindset: MINDSET_QUOTES,
  patience: PATIENCE_QUOTES,
  life: LIFE_QUOTES,
};

/** Simple deterministic string hash, so the same date always maps to the same quote. */
function hashString(s: string): number {
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = (hash * 31 + s.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

/**
 * One quote per day, the same for the whole day regardless of how many
 * times the app is opened. Cycles through the categories in a fixed
 * 10-day pattern (3x risk, 3x mindset, 3x patience, 1x life) so the mix
 * stays exactly 10% life over time, then picks a specific quote within
 * that day's category from a hash of the date - stable across restarts
 * without needing to store which quote was shown.
 */
export function getQuoteOfDay(dateKey: string): Quote {
  const dayNumber = Number(dateKey.replace(/-/g, ""));
  const category = CATEGORY_CYCLE[dayNumber % CATEGORY_CYCLE.length];
  const pool = QUOTES_BY_CATEGORY[category];
  const index = hashString(dateKey) % pool.length;
  return pool[index];
}
